import 'dart:math' as math;

import 'data.dart';

/// Identifies the origin or termination state of an emitted token.
///
/// During prompt ingestion, all prompt tokens are emitted with [prompt].
/// During autoregressive generation, newly sampled tokens are emitted with
/// [generated].
///
/// The special values [eos] and [maxTokensReached] may optionally be emitted
/// as terminal notifications to signal why generation stopped.
enum TokenOrigin {
  /// Token belongs to the original prompt being ingested by the model.
  prompt,

  /// Token was generated by the model during sampling.
  generated,

  /// Generation stopped because the model emitted the EOS token.
  eos,

  /// Generation stopped because the configured maximum token count was reached.
  maxTokensReached;

  /// Whether this emitted token marks the end of generation.
  ///
  /// Returns `true` for terminal emission events such as:
  /// - [TokenOrigin.eos]: the model emitted the end-of-sequence token.
  /// - [TokenOrigin.maxTokensReached]: generation stopped because the
  ///   configured maximum number of output tokens was reached.
  ///
  /// Returns `false` for normal prompt or generated tokens.
  bool get isTerminal {
    switch (this) {
      case TokenOrigin.eos:
      case TokenOrigin.maxTokensReached:
        return true;
      default:
        return false;
    }
  }
}

/// Callback invoked whenever a token is emitted by the inference engine.
///
/// [tokenId] is the raw integer token id from the tokenizer vocabulary.
///
/// [tokenText] is the decoded textual representation associated with that token.
/// Depending on the tokenizer, this may be:
/// - a full word,
/// - a word fragment,
/// - whitespace,
/// - punctuation,
/// - or a partial UTF-8 piece.
///
/// [origin] indicates whether the token comes from prompt ingestion, normal
/// generation, or a terminal stop notification.
typedef OnTokenEmitted =
    void Function(int tokenId, String tokenText, TokenOrigin origin);

/// Describes why token generation finished.
enum TokenGenerationStopReason {
  /// Generation stopped because the model naturally emitted the EOS token.
  eosToken,

  /// Generation stopped because the configured [maxTokens] limit was reached.
  maxTokensReached,
}

/// Immutable result object returned after a token generation session.
///
/// Contains:
/// - generated output text,
/// - generation parameters,
/// - token counts,
/// - timing measurements,
/// - throughput statistics,
/// - and the final stop reason.
class TokenGenerationResult {
  /// Original prompt text supplied to the model.
  final String prompt;

  /// Final generated output.
  ///
  /// Depending on the [includePromptInOutput] setting used during generation,
  /// this may contain:
  /// - only generated completion text, or
  /// - prompt + generated completion.
  final String output;

  /// Random seed used to initialize [random] for token sampling.
  final int seed;

  /// Pseudorandom number generator used during token sampling.
  final math.Random random;

  /// Maximum number of generated tokens requested.
  final int maxTokens;

  /// Temperature used during token sampling.
  final double temperature;

  /// Repeat penalty used to discourage repetitive token emission.
  final double repeatPenalty;

  /// Token IDs produced from the ingested [prompt].
  final List<int> promptTokens;

  /// Total number of prompt tokens consumed during ingestion.
  /// See [promptTokens].
  int get promptTokensLength => promptTokens.length;

  /// Token IDs generated by the model during sampling ([output]).
  final List<int> generatedTokens;

  /// Total number of tokens generated during sampling.
  /// See [generatedTokens]
  int get generatedTokensLength => generatedTokens.length;

  /// Total processed token count: [promptTokensLength] + [generatedTokensLength].
  int get totalTokens => promptTokensLength + generatedTokensLength;

  /// Time spent ingesting the prompt into the transformer KV cache.
  final Duration promptDuration;

  /// Time spent generating sampled tokens.
  final Duration generationDuration;

  /// Total generation session duration.
  final Duration totalDuration;

  /// Prompt ingestion throughput in tokens per second.
  final double promptTokensPerSecond;

  /// Generation throughput in tokens per second.
  final double generatedTokensPerSecond;

  /// Final reason why generation stopped.
  final TokenGenerationStopReason stopReason;

  /// Creates a token generation result.
  const TokenGenerationResult({
    required this.prompt,
    required this.output,
    required this.seed,
    required this.random,
    required this.maxTokens,
    required this.temperature,
    required this.repeatPenalty,
    required this.promptTokens,
    required this.generatedTokens,
    required this.promptDuration,
    required this.generationDuration,
    required this.totalDuration,
    required this.promptTokensPerSecond,
    required this.generatedTokensPerSecond,
    required this.stopReason,
  });

  /// Total end-to-end throughput in tokens per second.
  double get totalTokensPerSecond {
    var secs = totalDuration.inMicroseconds / 1000000.0;
    return secs == 0 ? 0.0 : totalTokens / secs;
  }

  /// Builds a formatted multi-line human-readable statistics report.
  ///
  /// Useful for:
  /// - logging,
  /// - benchmarks,
  /// - performance diagnostics,
  /// - inference summaries.
  String statsSummary() {
    return '''
=== Token Generation Stats ===
prompt.length    : ${prompt.length}
output.length    : ${output.length}

seed             : $seed
maxTokens        : $maxTokens
temperature      : $temperature
repeatPenalty    : $repeatPenalty

stop reason      : $stopReason

prompt tokens    : $promptTokensLength
generated tokens : $generatedTokensLength
total tokens     : $totalTokens

prompt ingest    : ${promptDuration.formattedToSeconds} s (${promptTokensPerSecond.toStringAsFixed(2)} tk/s)
generation       : ${generationDuration.formattedToSeconds} s (${generatedTokensPerSecond.toStringAsFixed(2)} tk/s)
total            : ${totalDuration.formattedToSeconds} s (${totalTokensPerSecond.toStringAsFixed(2)} tk/s)
''';
  }

  /// Returns only the generated output text.
  @override
  String toString() => output;
}

/// Base contract for language model token generators.
abstract class TokenGenerator {
  /// Default maximum number of tokens generated per request.
  static const defaultMaxTokens = 1024 * 2;

  /// Default sampling temperature.
  static const defaultTemperature = 0.1;

  /// Default sampling temperature for chat sessions.
  static const defaultChatTemperature = 0.2;

  /// Default repeat penalty applied during sampling.
  static const defaultRepeatPenalty = 1.09;

  /// Default repeat penalty applied during chat sessions.
  static const defaultChatRepeatPenalty = 1.0;

  /// Generates text from the given [prompt].
  ///
  /// [maxTokens] limits the number of newly generated tokens.
  ///
  /// [temperature] controls randomness:
  /// - lower values produce more deterministic output,
  /// - higher values produce more diverse output.
  ///
  /// [repeatPenalty] discourages repeated token repetition.
  ///
  /// [seed] optionally forces deterministic reproducible sampling.
  ///
  /// [emmitPromptTokens] controls whether prompt tokens are also emitted to
  /// [onTokenEmitted] during prompt ingestion.
  ///
  /// [includePromptInOutput] controls whether [TokenGenerationResult.output]
  /// includes the original prompt text.
  ///
  /// [onTokenEmitted] receives streaming token notifications during prompt
  /// ingestion and generation.
  ///
  /// [random] optionally supplies a custom random number generator.
  Future<TokenGenerationResult> generate(
    String prompt, {
    int maxTokens = defaultMaxTokens,
    double temperature = defaultTemperature,
    double repeatPenalty = defaultRepeatPenalty,
    int? seed,
    bool emmitPromptTokens = true,
    bool includePromptInOutput = true,
    OnTokenEmitted? onTokenEmitted,
    math.Random? random,
  });
}
